(define (space get-life)
  (:literals (alive candace)
             (alive character)
             (alive female-)
             (alive male)
             (alive mary)
             (alive sam)
             (alive william)
             (at candace denver)
             (not (at candace denver))
             (at candace idaho)
             (not (at candace idaho))
             (at candace new-orleans)
             (not (at candace new-orleans))
             (at character denver)
             (not (at character denver))
             (at character idaho)
             (not (at character idaho))
             (at character new-orleans)
             (not (at character new-orleans))
             (at female- denver)
             (not (at female- denver))
             (at female- idaho)
             (not (at female- idaho))
             (at female- new-orleans)
             (not (at female- new-orleans))
             (at male denver)
             (not (at male denver))
             (at male idaho)
             (not (at male idaho))
             (at male new-orleans)
             (not (at male new-orleans))
             (at mary denver)
             (not (at mary denver))
             (at mary idaho)
             (not (at mary idaho))
             (at mary new-orleans)
             (not (at mary new-orleans))
             (at sam denver)
             (not (at sam denver))
             (at sam idaho)
             (not (at sam idaho))
             (at sam new-orleans)
             (not (at sam new-orleans))
             (at william denver)
             (not (at william denver))
             (at william idaho)
             (not (at william idaho))
             (at william new-orleans)
             (not (at william new-orleans))
             (attending candace denver farm)
             (not (attending candace denver farm))
             (attending candace denver google)
             (not (attending candace denver google))
             (attending candace denver stanford)
             (not (attending candace denver stanford))
             (attending candace denver university-denver)
             (not (attending candace denver university-denver))
             (attending candace idaho farm)
             (not (attending candace idaho farm))
             (attending candace idaho google)
             (not (attending candace idaho google))
             (attending candace idaho stanford)
             (not (attending candace idaho stanford))
             (attending candace idaho university-denver)
             (not (attending candace idaho university-denver))
             (attending candace new-orleans farm)
             (not (attending candace new-orleans farm))
             (attending candace new-orleans google)
             (not (attending candace new-orleans google))
             (attending candace new-orleans stanford)
             (not (attending candace new-orleans stanford))
             (attending candace new-orleans university-denver)
             (not (attending candace new-orleans university-denver))
             (attending character denver farm)
             (not (attending character denver farm))
             (attending character denver google)
             (not (attending character denver google))
             (attending character denver stanford)
             (not (attending character denver stanford))
             (attending character denver university-denver)
             (not (attending character denver university-denver))
             (attending character idaho farm)
             (not (attending character idaho farm))
             (attending character idaho google)
             (not (attending character idaho google))
             (attending character idaho stanford)
             (not (attending character idaho stanford))
             (attending character idaho university-denver)
             (not (attending character idaho university-denver))
             (attending character new-orleans farm)
             (not (attending character new-orleans farm))
             (attending character new-orleans google)
             (not (attending character new-orleans google))
             (attending character new-orleans stanford)
             (not (attending character new-orleans stanford))
             (attending character new-orleans university-denver)
             (not (attending character new-orleans university-denver))
             (attending female- denver farm)
             (not (attending female- denver farm))
             (attending female- denver google)
             (not (attending female- denver google))
             (attending female- denver stanford)
             (not (attending female- denver stanford))
             (attending female- denver university-denver)
             (not (attending female- denver university-denver))
             (attending female- idaho farm)
             (not (attending female- idaho farm))
             (attending female- idaho google)
             (not (attending female- idaho google))
             (attending female- idaho stanford)
             (not (attending female- idaho stanford))
             (attending female- idaho university-denver)
             (not (attending female- idaho university-denver))
             (attending female- new-orleans farm)
             (not (attending female- new-orleans farm))
             (attending female- new-orleans google)
             (not (attending female- new-orleans google))
             (attending female- new-orleans stanford)
             (not (attending female- new-orleans stanford))
             (attending female- new-orleans university-denver)
             (not (attending female- new-orleans university-denver))
             (attending male denver farm)
             (not (attending male denver farm))
             (attending male denver google)
             (not (attending male denver google))
             (attending male denver stanford)
             (not (attending male denver stanford))
             (attending male denver university-denver)
             (not (attending male denver university-denver))
             (attending male idaho farm)
             (not (attending male idaho farm))
             (attending male idaho google)
             (not (attending male idaho google))
             (attending male idaho stanford)
             (not (attending male idaho stanford))
             (attending male idaho university-denver)
             (not (attending male idaho university-denver))
             (attending male new-orleans farm)
             (not (attending male new-orleans farm))
             (attending male new-orleans google)
             (not (attending male new-orleans google))
             (attending male new-orleans stanford)
             (not (attending male new-orleans stanford))
             (attending male new-orleans university-denver)
             (not (attending male new-orleans university-denver))
             (attending mary denver farm)
             (not (attending mary denver farm))
             (attending mary denver google)
             (not (attending mary denver google))
             (attending mary denver stanford)
             (not (attending mary denver stanford))
             (attending mary denver university-denver)
             (not (attending mary denver university-denver))
             (attending mary idaho farm)
             (not (attending mary idaho farm))
             (attending mary idaho google)
             (not (attending mary idaho google))
             (attending mary idaho stanford)
             (not (attending mary idaho stanford))
             (attending mary idaho university-denver)
             (not (attending mary idaho university-denver))
             (attending mary new-orleans farm)
             (not (attending mary new-orleans farm))
             (attending mary new-orleans google)
             (not (attending mary new-orleans google))
             (attending mary new-orleans stanford)
             (not (attending mary new-orleans stanford))
             (attending mary new-orleans university-denver)
             (not (attending mary new-orleans university-denver))
             (attending sam denver farm)
             (not (attending sam denver farm))
             (attending sam denver google)
             (not (attending sam denver google))
             (attending sam denver stanford)
             (not (attending sam denver stanford))
             (attending sam denver university-denver)
             (not (attending sam denver university-denver))
             (attending sam idaho farm)
             (not (attending sam idaho farm))
             (attending sam idaho google)
             (not (attending sam idaho google))
             (attending sam idaho stanford)
             (not (attending sam idaho stanford))
             (attending sam idaho university-denver)
             (not (attending sam idaho university-denver))
             (attending sam new-orleans farm)
             (not (attending sam new-orleans farm))
             (attending sam new-orleans google)
             (not (attending sam new-orleans google))
             (attending sam new-orleans stanford)
             (not (attending sam new-orleans stanford))
             (attending sam new-orleans university-denver)
             (not (attending sam new-orleans university-denver))
             (attending william denver farm)
             (not (attending william denver farm))
             (attending william denver google)
             (not (attending william denver google))
             (attending william denver stanford)
             (not (attending william denver stanford))
             (attending william denver university-denver)
             (not (attending william denver university-denver))
             (attending william idaho farm)
             (not (attending william idaho farm))
             (attending william idaho google)
             (not (attending william idaho google))
             (attending william idaho stanford)
             (not (attending william idaho stanford))
             (attending william idaho university-denver)
             (not (attending william idaho university-denver))
             (attending william new-orleans farm)
             (not (attending william new-orleans farm))
             (attending william new-orleans google)
             (not (attending william new-orleans google))
             (attending william new-orleans stanford)
             (not (attending william new-orleans stanford))
             (attending william new-orleans university-denver)
             (not (attending william new-orleans university-denver))
             (exists farm)
             (exists google)
             (exists stanford)
             (exists university-denver)
             (grown-up candace)
             (not (grown-up candace))
             (grown-up character)
             (not (grown-up character))
             (grown-up female-)
             (not (grown-up female-))
             (grown-up male)
             (not (grown-up male))
             (grown-up mary)
             (not (grown-up mary))
             (grown-up sam)
             (not (grown-up sam))
             (grown-up william)
             (not (grown-up william))
             (hasaccepted farm candace)
             (not (hasaccepted farm candace))
             (hasaccepted farm character)
             (not (hasaccepted farm character))
             (hasaccepted farm female-)
             (not (hasaccepted farm female-))
             (hasaccepted farm male)
             (not (hasaccepted farm male))
             (hasaccepted farm mary)
             (not (hasaccepted farm mary))
             (hasaccepted farm sam)
             (not (hasaccepted farm sam))
             (hasaccepted farm william)
             (not (hasaccepted farm william))
             (hasaccepted google candace)
             (not (hasaccepted google candace))
             (hasaccepted google character)
             (not (hasaccepted google character))
             (hasaccepted google female-)
             (not (hasaccepted google female-))
             (hasaccepted google male)
             (not (hasaccepted google male))
             (hasaccepted google mary)
             (not (hasaccepted google mary))
             (hasaccepted google sam)
             (not (hasaccepted google sam))
             (hasaccepted google william)
             (not (hasaccepted google william))
             (hasaccepted stanford candace)
             (not (hasaccepted stanford candace))
             (hasaccepted stanford character)
             (not (hasaccepted stanford character))
             (hasaccepted stanford female-)
             (not (hasaccepted stanford female-))
             (hasaccepted stanford male)
             (not (hasaccepted stanford male))
             (hasaccepted stanford mary)
             (not (hasaccepted stanford mary))
             (hasaccepted stanford sam)
             (not (hasaccepted stanford sam))
             (hasaccepted stanford william)
             (not (hasaccepted stanford william))
             (hasaccepted university-denver candace)
             (not (hasaccepted university-denver candace))
             (hasaccepted university-denver character)
             (not (hasaccepted university-denver character))
             (hasaccepted university-denver female-)
             (not (hasaccepted university-denver female-))
             (hasaccepted university-denver male)
             (not (hasaccepted university-denver male))
             (hasaccepted university-denver mary)
             (not (hasaccepted university-denver mary))
             (hasaccepted university-denver sam)
             (not (hasaccepted university-denver sam))
             (hasaccepted university-denver william)
             (not (hasaccepted university-denver william))
             (hasapplied candace farm)
             (hasapplied candace google)
             (hasapplied candace stanford)
             (hasapplied candace university-denver)
             (hasapplied character farm)
             (hasapplied character google)
             (hasapplied character stanford)
             (hasapplied character university-denver)
             (hasapplied female- farm)
             (hasapplied female- google)
             (hasapplied female- stanford)
             (hasapplied female- university-denver)
             (hasapplied male farm)
             (hasapplied male google)
             (hasapplied male stanford)
             (hasapplied male university-denver)
             (hasapplied mary farm)
             (hasapplied mary google)
             (hasapplied mary stanford)
             (hasapplied mary university-denver)
             (hasapplied sam farm)
             (hasapplied sam google)
             (hasapplied sam stanford)
             (hasapplied sam university-denver)
             (hasapplied william farm)
             (hasapplied william google)
             (hasapplied william stanford)
             (hasapplied william university-denver)
             (hasrejected farm candace)
             (not (hasrejected farm candace))
             (hasrejected farm character)
             (not (hasrejected farm character))
             (hasrejected farm female-)
             (not (hasrejected farm female-))
             (hasrejected farm male)
             (not (hasrejected farm male))
             (hasrejected farm mary)
             (not (hasrejected farm mary))
             (hasrejected farm sam)
             (not (hasrejected farm sam))
             (hasrejected farm william)
             (not (hasrejected farm william))
             (hasrejected google candace)
             (not (hasrejected google candace))
             (hasrejected google character)
             (not (hasrejected google character))
             (hasrejected google female-)
             (not (hasrejected google female-))
             (hasrejected google male)
             (not (hasrejected google male))
             (hasrejected google mary)
             (not (hasrejected google mary))
             (hasrejected google sam)
             (not (hasrejected google sam))
             (hasrejected google william)
             (not (hasrejected google william))
             (hasrejected stanford candace)
             (not (hasrejected stanford candace))
             (hasrejected stanford character)
             (not (hasrejected stanford character))
             (hasrejected stanford female-)
             (not (hasrejected stanford female-))
             (hasrejected stanford male)
             (not (hasrejected stanford male))
             (hasrejected stanford mary)
             (not (hasrejected stanford mary))
             (hasrejected stanford sam)
             (not (hasrejected stanford sam))
             (hasrejected stanford william)
             (not (hasrejected stanford william))
             (hasrejected university-denver candace)
             (not (hasrejected university-denver candace))
             (hasrejected university-denver character)
             (not (hasrejected university-denver character))
             (hasrejected university-denver female-)
             (not (hasrejected university-denver female-))
             (hasrejected university-denver male)
             (not (hasrejected university-denver male))
             (hasrejected university-denver mary)
             (not (hasrejected university-denver mary))
             (hasrejected university-denver sam)
             (not (hasrejected university-denver sam))
             (hasrejected university-denver william)
             (not (hasrejected university-denver william))
             (intends candace (married candace))
             (intends candace (marriedto candace character))
             (intends candace (marriedto candace female-))
             (intends candace (marriedto candace male))
             (intends candace (marriedto candace sam))
             (intends candace (marriedto candace william))
             (intends character (marriedto character candace))
             (intends character (marriedto character mary))
             (intends female- (marriedto female- candace))
             (intends female- (marriedto female- mary))
             (intends google (hasaccepted google sam))
             (intends male (marriedto male candace))
             (intends male (marriedto male mary))
             (intends mary (marriedto mary character))
             (intends mary (marriedto mary female-))
             (intends mary (marriedto mary male))
             (intends mary (marriedto mary sam))
             (intends mary (marriedto mary william))
             (intends sam (at sam denver))
             (intends sam (hasapplied sam google))
             (intends sam (marriedto sam candace))
             (intends sam (marriedto sam mary))
             (intends william (married william))
             (intends william (marriedto william candace))
             (intends william (marriedto william mary))
             (isbetter candace)
             (isbetter character)
             (isbetter female-)
             (isbetter male)
             (isbetter mary)
             (isbetter sam)
             (isbetter william)
             (issick candace)
             (not (issick candace))
             (issick character)
             (not (issick character))
             (issick female-)
             (not (issick female-))
             (issick male)
             (not (issick male))
             (issick mary)
             (not (issick mary))
             (issick sam)
             (not (issick sam))
             (issick william)
             (not (issick william))
             (knows candace candace)
             (not (knows candace candace))
             (knows candace character)
             (not (knows candace character))
             (knows candace female-)
             (not (knows candace female-))
             (knows candace male)
             (not (knows candace male))
             (knows candace mary)
             (not (knows candace mary))
             (knows candace sam)
             (not (knows candace sam))
             (knows candace william)
             (not (knows candace william))
             (knows character candace)
             (not (knows character candace))
             (knows character character)
             (not (knows character character))
             (knows character female-)
             (not (knows character female-))
             (knows character male)
             (not (knows character male))
             (knows character mary)
             (not (knows character mary))
             (knows character sam)
             (not (knows character sam))
             (knows character william)
             (not (knows character william))
             (knows female- candace)
             (not (knows female- candace))
             (knows female- character)
             (not (knows female- character))
             (knows female- female-)
             (not (knows female- female-))
             (knows female- male)
             (not (knows female- male))
             (knows female- mary)
             (not (knows female- mary))
             (knows female- sam)
             (not (knows female- sam))
             (knows female- william)
             (not (knows female- william))
             (knows male candace)
             (not (knows male candace))
             (knows male character)
             (not (knows male character))
             (knows male female-)
             (not (knows male female-))
             (knows male male)
             (not (knows male male))
             (knows male mary)
             (not (knows male mary))
             (knows male sam)
             (not (knows male sam))
             (knows male william)
             (not (knows male william))
             (knows mary candace)
             (not (knows mary candace))
             (knows mary character)
             (not (knows mary character))
             (knows mary female-)
             (not (knows mary female-))
             (knows mary male)
             (not (knows mary male))
             (knows mary mary)
             (not (knows mary mary))
             (knows mary sam)
             (not (knows mary sam))
             (knows mary william)
             (not (knows mary william))
             (knows sam candace)
             (not (knows sam candace))
             (knows sam character)
             (not (knows sam character))
             (knows sam female-)
             (not (knows sam female-))
             (knows sam male)
             (not (knows sam male))
             (knows sam mary)
             (not (knows sam mary))
             (knows sam sam)
             (not (knows sam sam))
             (knows sam william)
             (not (knows sam william))
             (knows william candace)
             (not (knows william candace))
             (knows william character)
             (not (knows william character))
             (knows william female-)
             (not (knows william female-))
             (knows william male)
             (not (knows william male))
             (knows william mary)
             (not (knows william mary))
             (knows william sam)
             (not (knows william sam))
             (knows william william)
             (not (knows william william))
             (loves candace character)
             (not (loves candace character))
             (loves candace female-)
             (not (loves candace female-))
             (loves candace male)
             (not (loves candace male))
             (loves candace sam)
             (not (loves candace sam))
             (loves candace william)
             (not (loves candace william))
             (loves character candace)
             (not (loves character candace))
             (loves character mary)
             (not (loves character mary))
             (loves female- candace)
             (not (loves female- candace))
             (loves female- mary)
             (not (loves female- mary))
             (loves male candace)
             (not (loves male candace))
             (loves male mary)
             (not (loves male mary))
             (loves mary character)
             (not (loves mary character))
             (loves mary female-)
             (not (loves mary female-))
             (loves mary male)
             (not (loves mary male))
             (loves mary sam)
             (not (loves mary sam))
             (loves mary william)
             (not (loves mary william))
             (loves sam candace)
             (not (loves sam candace))
             (loves sam mary)
             (not (loves sam mary))
             (loves william candace)
             (not (loves william candace))
             (loves william mary)
             (not (loves william mary))
             (married candace)
             (not (married candace))
             (married character)
             (not (married character))
             (married female-)
             (not (married female-))
             (married male)
             (not (married male))
             (married mary)
             (not (married mary))
             (married sam)
             (not (married sam))
             (married william)
             (not (married william))
             (marriedto candace character)
             (marriedto candace female-)
             (marriedto candace male)
             (marriedto candace sam)
             (marriedto candace william)
             (marriedto character candace)
             (marriedto character mary)
             (marriedto female- candace)
             (marriedto female- mary)
             (marriedto male candace)
             (marriedto male mary)
             (marriedto mary character)
             (marriedto mary female-)
             (marriedto mary male)
             (marriedto mary sam)
             (marriedto mary william)
             (marriedto sam candace)
             (marriedto sam mary)
             (marriedto william candace)
             (marriedto william mary))
  (:steps (move male new-orleans denver)
          (move male new-orleans idaho)
          (move male denver new-orleans)
          (move male denver idaho)
          (move male idaho new-orleans)
          (move male idaho denver)
          (move female- new-orleans denver)
          (move female- new-orleans idaho)
          (move female- denver new-orleans)
          (move female- denver idaho)
          (move female- idaho new-orleans)
          (move female- idaho denver)
          (move character new-orleans denver)
          (move character new-orleans idaho)
          (move character denver new-orleans)
          (move character denver idaho)
          (move character idaho new-orleans)
          (move character idaho denver)
          (move william new-orleans denver)
          (move william new-orleans idaho)
          (move william denver new-orleans)
          (move william denver idaho)
          (move william idaho new-orleans)
          (move william idaho denver)
          (move sam new-orleans denver)
          (move sam new-orleans idaho)
          (move sam denver new-orleans)
          (move sam denver idaho)
          (move sam idaho new-orleans)
          (move sam idaho denver)
          (move mary new-orleans denver)
          (move mary new-orleans idaho)
          (move mary denver new-orleans)
          (move mary denver idaho)
          (move mary idaho new-orleans)
          (move mary idaho denver)
          (move candace new-orleans denver)
          (move candace new-orleans idaho)
          (move candace denver new-orleans)
          (move candace denver idaho)
          (move candace idaho new-orleans)
          (move candace idaho denver)
          (apply male stanford)
          (apply male university-denver)
          (apply male google)
          (apply male farm)
          (apply female- stanford)
          (apply female- university-denver)
          (apply female- google)
          (apply female- farm)
          (apply character stanford)
          (apply character university-denver)
          (apply character google)
          (apply character farm)
          (apply william stanford)
          (apply william university-denver)
          (apply william google)
          (apply william farm)
          (apply sam stanford)
          (apply sam university-denver)
          (apply sam google)
          (apply sam farm)
          (apply mary stanford)
          (apply mary university-denver)
          (apply mary google)
          (apply mary farm)
          (apply candace stanford)
          (apply candace university-denver)
          (apply candace google)
          (apply candace farm)
          (accept stanford male)
          (accept stanford female-)
          (accept stanford character)
          (accept stanford william)
          (accept stanford sam)
          (accept stanford mary)
          (accept stanford candace)
          (accept university-denver male)
          (accept university-denver female-)
          (accept university-denver character)
          (accept university-denver william)
          (accept university-denver sam)
          (accept university-denver mary)
          (accept university-denver candace)
          (accept google male)
          (accept google female-)
          (accept google character)
          (accept google william)
          (accept google sam)
          (accept google mary)
          (accept google candace)
          (accept farm male)
          (accept farm female-)
          (accept farm character)
          (accept farm william)
          (accept farm sam)
          (accept farm mary)
          (accept farm candace)
          (reject stanford male)
          (reject stanford female-)
          (reject stanford character)
          (reject stanford william)
          (reject stanford sam)
          (reject stanford mary)
          (reject stanford candace)
          (reject university-denver male)
          (reject university-denver female-)
          (reject university-denver character)
          (reject university-denver william)
          (reject university-denver sam)
          (reject university-denver mary)
          (reject university-denver candace)
          (reject google male)
          (reject google female-)
          (reject google character)
          (reject google william)
          (reject google sam)
          (reject google mary)
          (reject google candace)
          (reject farm male)
          (reject farm female-)
          (reject farm character)
          (reject farm william)
          (reject farm sam)
          (reject farm mary)
          (reject farm candace)
          (attend male new-orleans stanford)
          (attend male new-orleans university-denver)
          (attend male new-orleans google)
          (attend male new-orleans farm)
          (attend male denver stanford)
          (attend male denver university-denver)
          (attend male denver google)
          (attend male denver farm)
          (attend male idaho stanford)
          (attend male idaho university-denver)
          (attend male idaho google)
          (attend male idaho farm)
          (attend female- new-orleans stanford)
          (attend female- new-orleans university-denver)
          (attend female- new-orleans google)
          (attend female- new-orleans farm)
          (attend female- denver stanford)
          (attend female- denver university-denver)
          (attend female- denver google)
          (attend female- denver farm)
          (attend female- idaho stanford)
          (attend female- idaho university-denver)
          (attend female- idaho google)
          (attend female- idaho farm)
          (attend character new-orleans stanford)
          (attend character new-orleans university-denver)
          (attend character new-orleans google)
          (attend character new-orleans farm)
          (attend character denver stanford)
          (attend character denver university-denver)
          (attend character denver google)
          (attend character denver farm)
          (attend character idaho stanford)
          (attend character idaho university-denver)
          (attend character idaho google)
          (attend character idaho farm)
          (attend william new-orleans stanford)
          (attend william new-orleans university-denver)
          (attend william new-orleans google)
          (attend william new-orleans farm)
          (attend william denver stanford)
          (attend william denver university-denver)
          (attend william denver google)
          (attend william denver farm)
          (attend william idaho stanford)
          (attend william idaho university-denver)
          (attend william idaho google)
          (attend william idaho farm)
          (attend sam new-orleans stanford)
          (attend sam new-orleans university-denver)
          (attend sam new-orleans google)
          (attend sam new-orleans farm)
          (attend sam denver stanford)
          (attend sam denver university-denver)
          (attend sam denver google)
          (attend sam denver farm)
          (attend sam idaho stanford)
          (attend sam idaho university-denver)
          (attend sam idaho google)
          (attend sam idaho farm)
          (attend mary new-orleans stanford)
          (attend mary new-orleans university-denver)
          (attend mary new-orleans google)
          (attend mary new-orleans farm)
          (attend mary denver stanford)
          (attend mary denver university-denver)
          (attend mary denver google)
          (attend mary denver farm)
          (attend mary idaho stanford)
          (attend mary idaho university-denver)
          (attend mary idaho google)
          (attend mary idaho farm)
          (attend candace new-orleans stanford)
          (attend candace new-orleans university-denver)
          (attend candace new-orleans google)
          (attend candace new-orleans farm)
          (attend candace denver stanford)
          (attend candace denver university-denver)
          (attend candace denver google)
          (attend candace denver farm)
          (attend candace idaho stanford)
          (attend candace idaho university-denver)
          (attend candace idaho google)
          (attend candace idaho farm)
          (gets-sick male)
          (gets-sick female-)
          (gets-sick character)
          (gets-sick william)
          (gets-sick sam)
          (gets-sick mary)
          (gets-sick candace)
          (cares-for male male)
          (cares-for male female-)
          (cares-for male character)
          (cares-for male william)
          (cares-for male sam)
          (cares-for male mary)
          (cares-for male candace)
          (cares-for female- male)
          (cares-for female- female-)
          (cares-for female- character)
          (cares-for female- william)
          (cares-for female- sam)
          (cares-for female- mary)
          (cares-for female- candace)
          (cares-for character male)
          (cares-for character female-)
          (cares-for character character)
          (cares-for character william)
          (cares-for character sam)
          (cares-for character mary)
          (cares-for character candace)
          (cares-for william male)
          (cares-for william female-)
          (cares-for william character)
          (cares-for william william)
          (cares-for william sam)
          (cares-for william mary)
          (cares-for william candace)
          (cares-for sam male)
          (cares-for sam female-)
          (cares-for sam character)
          (cares-for sam william)
          (cares-for sam sam)
          (cares-for sam mary)
          (cares-for sam candace)
          (cares-for mary male)
          (cares-for mary female-)
          (cares-for mary character)
          (cares-for mary william)
          (cares-for mary sam)
          (cares-for mary mary)
          (cares-for mary candace)
          (cares-for candace male)
          (cares-for candace female-)
          (cares-for candace character)
          (cares-for candace william)
          (cares-for candace sam)
          (cares-for candace mary)
          (cares-for candace candace)
          (meet male male new-orleans)
          (meet male male denver)
          (meet male male idaho)
          (meet male female- new-orleans)
          (meet male female- denver)
          (meet male female- idaho)
          (meet male character new-orleans)
          (meet male character denver)
          (meet male character idaho)
          (meet male william new-orleans)
          (meet male william denver)
          (meet male william idaho)
          (meet male sam new-orleans)
          (meet male sam denver)
          (meet male sam idaho)
          (meet male mary new-orleans)
          (meet male mary denver)
          (meet male mary idaho)
          (meet male candace new-orleans)
          (meet male candace denver)
          (meet male candace idaho)
          (meet female- male new-orleans)
          (meet female- male denver)
          (meet female- male idaho)
          (meet female- female- new-orleans)
          (meet female- female- denver)
          (meet female- female- idaho)
          (meet female- character new-orleans)
          (meet female- character denver)
          (meet female- character idaho)
          (meet female- william new-orleans)
          (meet female- william denver)
          (meet female- william idaho)
          (meet female- sam new-orleans)
          (meet female- sam denver)
          (meet female- sam idaho)
          (meet female- mary new-orleans)
          (meet female- mary denver)
          (meet female- mary idaho)
          (meet female- candace new-orleans)
          (meet female- candace denver)
          (meet female- candace idaho)
          (meet character male new-orleans)
          (meet character male denver)
          (meet character male idaho)
          (meet character female- new-orleans)
          (meet character female- denver)
          (meet character female- idaho)
          (meet character character new-orleans)
          (meet character character denver)
          (meet character character idaho)
          (meet character william new-orleans)
          (meet character william denver)
          (meet character william idaho)
          (meet character sam new-orleans)
          (meet character sam denver)
          (meet character sam idaho)
          (meet character mary new-orleans)
          (meet character mary denver)
          (meet character mary idaho)
          (meet character candace new-orleans)
          (meet character candace denver)
          (meet character candace idaho)
          (meet william male new-orleans)
          (meet william male denver)
          (meet william male idaho)
          (meet william female- new-orleans)
          (meet william female- denver)
          (meet william female- idaho)
          (meet william character new-orleans)
          (meet william character denver)
          (meet william character idaho)
          (meet william william new-orleans)
          (meet william william denver)
          (meet william william idaho)
          (meet william sam new-orleans)
          (meet william sam denver)
          (meet william sam idaho)
          (meet william mary new-orleans)
          (meet william mary denver)
          (meet william mary idaho)
          (meet william candace new-orleans)
          (meet william candace denver)
          (meet william candace idaho)
          (meet sam male new-orleans)
          (meet sam male denver)
          (meet sam male idaho)
          (meet sam female- new-orleans)
          (meet sam female- denver)
          (meet sam female- idaho)
          (meet sam character new-orleans)
          (meet sam character denver)
          (meet sam character idaho)
          (meet sam william new-orleans)
          (meet sam william denver)
          (meet sam william idaho)
          (meet sam sam new-orleans)
          (meet sam sam denver)
          (meet sam sam idaho)
          (meet sam mary new-orleans)
          (meet sam mary denver)
          (meet sam mary idaho)
          (meet sam candace new-orleans)
          (meet sam candace denver)
          (meet sam candace idaho)
          (meet mary male new-orleans)
          (meet mary male denver)
          (meet mary male idaho)
          (meet mary female- new-orleans)
          (meet mary female- denver)
          (meet mary female- idaho)
          (meet mary character new-orleans)
          (meet mary character denver)
          (meet mary character idaho)
          (meet mary william new-orleans)
          (meet mary william denver)
          (meet mary william idaho)
          (meet mary sam new-orleans)
          (meet mary sam denver)
          (meet mary sam idaho)
          (meet mary mary new-orleans)
          (meet mary mary denver)
          (meet mary mary idaho)
          (meet mary candace new-orleans)
          (meet mary candace denver)
          (meet mary candace idaho)
          (meet candace male new-orleans)
          (meet candace male denver)
          (meet candace male idaho)
          (meet candace female- new-orleans)
          (meet candace female- denver)
          (meet candace female- idaho)
          (meet candace character new-orleans)
          (meet candace character denver)
          (meet candace character idaho)
          (meet candace william new-orleans)
          (meet candace william denver)
          (meet candace william idaho)
          (meet candace sam new-orleans)
          (meet candace sam denver)
          (meet candace sam idaho)
          (meet candace mary new-orleans)
          (meet candace mary denver)
          (meet candace mary idaho)
          (meet candace candace new-orleans)
          (meet candace candace denver)
          (meet candace candace idaho)
          (marry male mary new-orleans)
          (marry male mary denver)
          (marry male mary idaho)
          (marry male candace new-orleans)
          (marry male candace denver)
          (marry male candace idaho)
          (marry female- mary new-orleans)
          (marry female- mary denver)
          (marry female- mary idaho)
          (marry female- candace new-orleans)
          (marry female- candace denver)
          (marry female- candace idaho)
          (marry character mary new-orleans)
          (marry character mary denver)
          (marry character mary idaho)
          (marry character candace new-orleans)
          (marry character candace denver)
          (marry character candace idaho)
          (marry william mary new-orleans)
          (marry william mary denver)
          (marry william mary idaho)
          (marry william candace new-orleans)
          (marry william candace denver)
          (marry william candace idaho)
          (marry sam mary new-orleans)
          (marry sam mary denver)
          (marry sam mary idaho)
          (marry sam candace new-orleans)
          (marry sam candace denver)
          (marry sam candace idaho)
          (fall-in-love male mary new-orleans)
          (fall-in-love male mary denver)
          (fall-in-love male mary idaho)
          (fall-in-love male candace new-orleans)
          (fall-in-love male candace denver)
          (fall-in-love male candace idaho)
          (fall-in-love female- mary new-orleans)
          (fall-in-love female- mary denver)
          (fall-in-love female- mary idaho)
          (fall-in-love female- candace new-orleans)
          (fall-in-love female- candace denver)
          (fall-in-love female- candace idaho)
          (fall-in-love character mary new-orleans)
          (fall-in-love character mary denver)
          (fall-in-love character mary idaho)
          (fall-in-love character candace new-orleans)
          (fall-in-love character candace denver)
          (fall-in-love character candace idaho)
          (fall-in-love william mary new-orleans)
          (fall-in-love william mary denver)
          (fall-in-love william mary idaho)
          (fall-in-love william candace new-orleans)
          (fall-in-love william candace denver)
          (fall-in-love william candace idaho)
          (fall-in-love sam mary new-orleans)
          (fall-in-love sam mary denver)
          (fall-in-love sam mary idaho)
          (fall-in-love sam candace new-orleans)
          (fall-in-love sam candace denver)
          (fall-in-love sam candace idaho)
          (have-child male mary male new-orleans)
          (have-child male mary male denver)
          (have-child male mary male idaho)
          (have-child male mary female- new-orleans)
          (have-child male mary female- denver)
          (have-child male mary female- idaho)
          (have-child male mary character new-orleans)
          (have-child male mary character denver)
          (have-child male mary character idaho)
          (have-child male mary william new-orleans)
          (have-child male mary william denver)
          (have-child male mary william idaho)
          (have-child male mary sam new-orleans)
          (have-child male mary sam denver)
          (have-child male mary sam idaho)
          (have-child male mary mary new-orleans)
          (have-child male mary mary denver)
          (have-child male mary mary idaho)
          (have-child male mary candace new-orleans)
          (have-child male mary candace denver)
          (have-child male mary candace idaho)
          (have-child male candace male new-orleans)
          (have-child male candace male denver)
          (have-child male candace male idaho)
          (have-child male candace female- new-orleans)
          (have-child male candace female- denver)
          (have-child male candace female- idaho)
          (have-child male candace character new-orleans)
          (have-child male candace character denver)
          (have-child male candace character idaho)
          (have-child male candace william new-orleans)
          (have-child male candace william denver)
          (have-child male candace william idaho)
          (have-child male candace sam new-orleans)
          (have-child male candace sam denver)
          (have-child male candace sam idaho)
          (have-child male candace mary new-orleans)
          (have-child male candace mary denver)
          (have-child male candace mary idaho)
          (have-child male candace candace new-orleans)
          (have-child male candace candace denver)
          (have-child male candace candace idaho)
          (have-child female- mary male new-orleans)
          (have-child female- mary male denver)
          (have-child female- mary male idaho)
          (have-child female- mary female- new-orleans)
          (have-child female- mary female- denver)
          (have-child female- mary female- idaho)
          (have-child female- mary character new-orleans)
          (have-child female- mary character denver)
          (have-child female- mary character idaho)
          (have-child female- mary william new-orleans)
          (have-child female- mary william denver)
          (have-child female- mary william idaho)
          (have-child female- mary sam new-orleans)
          (have-child female- mary sam denver)
          (have-child female- mary sam idaho)
          (have-child female- mary mary new-orleans)
          (have-child female- mary mary denver)
          (have-child female- mary mary idaho)
          (have-child female- mary candace new-orleans)
          (have-child female- mary candace denver)
          (have-child female- mary candace idaho)
          (have-child female- candace male new-orleans)
          (have-child female- candace male denver)
          (have-child female- candace male idaho)
          (have-child female- candace female- new-orleans)
          (have-child female- candace female- denver)
          (have-child female- candace female- idaho)
          (have-child female- candace character new-orleans)
          (have-child female- candace character denver)
          (have-child female- candace character idaho)
          (have-child female- candace william new-orleans)
          (have-child female- candace william denver)
          (have-child female- candace william idaho)
          (have-child female- candace sam new-orleans)
          (have-child female- candace sam denver)
          (have-child female- candace sam idaho)
          (have-child female- candace mary new-orleans)
          (have-child female- candace mary denver)
          (have-child female- candace mary idaho)
          (have-child female- candace candace new-orleans)
          (have-child female- candace candace denver)
          (have-child female- candace candace idaho)
          (have-child character mary male new-orleans)
          (have-child character mary male denver)
          (have-child character mary male idaho)
          (have-child character mary female- new-orleans)
          (have-child character mary female- denver)
          (have-child character mary female- idaho)
          (have-child character mary character new-orleans)
          (have-child character mary character denver)
          (have-child character mary character idaho)
          (have-child character mary william new-orleans)
          (have-child character mary william denver)
          (have-child character mary william idaho)
          (have-child character mary sam new-orleans)
          (have-child character mary sam denver)
          (have-child character mary sam idaho)
          (have-child character mary mary new-orleans)
          (have-child character mary mary denver)
          (have-child character mary mary idaho)
          (have-child character mary candace new-orleans)
          (have-child character mary candace denver)
          (have-child character mary candace idaho)
          (have-child character candace male new-orleans)
          (have-child character candace male denver)
          (have-child character candace male idaho)
          (have-child character candace female- new-orleans)
          (have-child character candace female- denver)
          (have-child character candace female- idaho)
          (have-child character candace character new-orleans)
          (have-child character candace character denver)
          (have-child character candace character idaho)
          (have-child character candace william new-orleans)
          (have-child character candace william denver)
          (have-child character candace william idaho)
          (have-child character candace sam new-orleans)
          (have-child character candace sam denver)
          (have-child character candace sam idaho)
          (have-child character candace mary new-orleans)
          (have-child character candace mary denver)
          (have-child character candace mary idaho)
          (have-child character candace candace new-orleans)
          (have-child character candace candace denver)
          (have-child character candace candace idaho)
          (have-child william mary male new-orleans)
          (have-child william mary male denver)
          (have-child william mary male idaho)
          (have-child william mary female- new-orleans)
          (have-child william mary female- denver)
          (have-child william mary female- idaho)
          (have-child william mary character new-orleans)
          (have-child william mary character denver)
          (have-child william mary character idaho)
          (have-child william mary william new-orleans)
          (have-child william mary william denver)
          (have-child william mary william idaho)
          (have-child william mary sam new-orleans)
          (have-child william mary sam denver)
          (have-child william mary sam idaho)
          (have-child william mary mary new-orleans)
          (have-child william mary mary denver)
          (have-child william mary mary idaho)
          (have-child william mary candace new-orleans)
          (have-child william mary candace denver)
          (have-child william mary candace idaho)
          (have-child william candace male new-orleans)
          (have-child william candace male denver)
          (have-child william candace male idaho)
          (have-child william candace female- new-orleans)
          (have-child william candace female- denver)
          (have-child william candace female- idaho)
          (have-child william candace character new-orleans)
          (have-child william candace character denver)
          (have-child william candace character idaho)
          (have-child william candace william new-orleans)
          (have-child william candace william denver)
          (have-child william candace william idaho)
          (have-child william candace sam new-orleans)
          (have-child william candace sam denver)
          (have-child william candace sam idaho)
          (have-child william candace mary new-orleans)
          (have-child william candace mary denver)
          (have-child william candace mary idaho)
          (have-child william candace candace new-orleans)
          (have-child william candace candace denver)
          (have-child william candace candace idaho)
          (have-child sam mary male new-orleans)
          (have-child sam mary male denver)
          (have-child sam mary male idaho)
          (have-child sam mary female- new-orleans)
          (have-child sam mary female- denver)
          (have-child sam mary female- idaho)
          (have-child sam mary character new-orleans)
          (have-child sam mary character denver)
          (have-child sam mary character idaho)
          (have-child sam mary william new-orleans)
          (have-child sam mary william denver)
          (have-child sam mary william idaho)
          (have-child sam mary sam new-orleans)
          (have-child sam mary sam denver)
          (have-child sam mary sam idaho)
          (have-child sam mary mary new-orleans)
          (have-child sam mary mary denver)
          (have-child sam mary mary idaho)
          (have-child sam mary candace new-orleans)
          (have-child sam mary candace denver)
          (have-child sam mary candace idaho)
          (have-child sam candace male new-orleans)
          (have-child sam candace male denver)
          (have-child sam candace male idaho)
          (have-child sam candace female- new-orleans)
          (have-child sam candace female- denver)
          (have-child sam candace female- idaho)
          (have-child sam candace character new-orleans)
          (have-child sam candace character denver)
          (have-child sam candace character idaho)
          (have-child sam candace william new-orleans)
          (have-child sam candace william denver)
          (have-child sam candace william idaho)
          (have-child sam candace sam new-orleans)
          (have-child sam candace sam denver)
          (have-child sam candace sam idaho)
          (have-child sam candace mary new-orleans)
          (have-child sam candace mary denver)
          (have-child sam candace mary idaho)
          (have-child sam candace candace new-orleans)
          (have-child sam candace candace denver)
          (have-child sam candace candace idaho)
          (grow-up male)
          (grow-up female-)
          (grow-up character)
          (grow-up william)
          (grow-up sam)
          (grow-up mary)
          (grow-up candace))
  (:axioms))