(define (plan get-life-solution)
 
 (:problem get-life)
  
(:steps (marry william candace new-orleans)
				(have-child william candace sam)
				(grow-up sam)
				(apply sam stanford)
				(reject stanford sam)
				(apply sam university-denver)
				(accept university-denver sam)
				(move sam new-orleans denver) 
				(attend sam denver university-denver)
				(meet sam mary denver)
				(fall-in-love sam mary denver)
				(gets-sick mary)
				(cares-for sam mary)
				(apply sam google)
				(accept google sam)
				(attend sam denver google)
				(marry sam mary denver)
	)
)
