(define (plan get-life-solution)
  (:problem get-life)
  (:steps (marry william candace new-orleans)
          (have-child william candace sam new-orleans)
          (grow-up sam)
          (apply sam google)
          (move sam new-orleans denver)))